### ISSUE TITLE
Callback Error

### ISSUE THREAD

**Issue by dardub** [vanakenm/effinbot#3]
Hi. I tried to authorize your app on slack, but after hitting the Authorize button I get the Rails / Something Went Wrong page on the following url:

https://www.effinbot.com/oauth/callback?code=STUFF&state=

Are you hosting this app for others or do we need to host it ourselves?

Thanks!

**Comment by vanakenm** [comment]
Hi! This is supposed to be working (I got logs showing that some people did use it yesterday). Let me have a look, I'll come back to you ASAP (I'm hosting is on a small server)

**Comment by vanakenm** [comment]
Something clearly break on my side, my tokens are no more correctly set. I'll have a look but probably not before this weekend

**Comment by dardub** [comment]
Ok. No problem. Thanks for looking into it!

**Comment by vanakenm** [comment]
Good you try again? Should be fixed right now.

**Comment by dardub** [comment]
It works! Thanks!
